import { Maximize2, Pause, Play, RotateCcw } from 'lucide-react'
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../api'
import { IntersectionView } from '../components/IntersectionView'
import { MetricCard } from '../components/MetricCard'
import type { PageKey, SimulationFrame } from '../types'

export function PresentationMode({ frame, history, onNavigate }: { frame: SimulationFrame | null; history: SimulationFrame[]; onNavigate: (page: PageKey) => void }) {
  const fullscreen = () => document.documentElement.requestFullscreen?.()
  const control = async (action: 'pause' | 'resume') => { if (frame) await api(`/api/comparisons/${frame.experiment_id}/${action}`, { method: 'POST' }) }
  const speed = async (value: string) => { if (frame) await api(`/api/comparisons/${frame.experiment_id}/speed`, { method: 'POST', body: JSON.stringify({ speed: value }) }) }
  const chart = history.map((item) => ({ time: item.simulation_time, fixed: item.fixed.metrics.vehicles_remaining, dqn: item.dqn.metrics.vehicles_remaining }))
  return <div className="presentation-page"><header><div><h1>고정 주기 vs DQN</h1><p>동일 조건 SUMO 실시간 비교 실험</p></div><div className="presentation-time">시뮬레이션 시간 <strong>{(frame?.simulation_time ?? 0).toFixed(1)}초</strong></div><button onClick={fullscreen}><Maximize2 />전체 화면</button></header><div className="presentation-controls"><button onClick={() => void control('resume')}><Play />시작</button><button onClick={() => void control('pause')}><Pause />일시정지</button><button onClick={() => onNavigate('comparison')}><RotateCcw />초기화</button>{(['1', '2', '4', 'max'] as const).map((value) => <button key={value} onClick={() => void speed(value)}>{value === 'max' ? '최대' : `${value}x`}</button>)}</div><div className="presentation-intersections"><IntersectionView title="고정 주기" tone="fixed" side={frame?.fixed} bounds={frame?.network_bounds} /><IntersectionView title="DQN" tone="dqn" side={frame?.dqn} bounds={frame?.network_bounds} /></div><div className="presentation-metrics"><MetricCard label="고정 주기 평균 대기" value={(frame?.fixed.metrics.average_waiting ?? 0).toFixed(1)} unit="초" tone="fixed" /><MetricCard label="DQN 평균 대기" value={(frame?.dqn.metrics.average_waiting ?? 0).toFixed(1)} unit="초" tone="dqn" /><MetricCard label="고정 주기 대기 행렬" value={frame?.fixed.metrics.current_queue.toFixed(0) ?? 0} tone="fixed" /><MetricCard label="DQN 대기 행렬" value={frame?.dqn.metrics.current_queue.toFixed(0) ?? 0} tone="dqn" /><MetricCard label="고정 주기 통과량" value={frame?.fixed.metrics.throughput ?? 0} tone="fixed" /><MetricCard label="DQN 통과량" value={frame?.dqn.metrics.throughput ?? 0} tone="dqn" /></div>{frame ? <section className="presentation-chart"><h2>남은 차량</h2><ResponsiveContainer width="100%" height={220}><LineChart data={chart}><CartesianGrid stroke="#d9e2ea" vertical={false} /><XAxis dataKey="time" stroke="#64748b" /><YAxis stroke="#64748b" domain={[0, 'auto']} /><Tooltip contentStyle={{ background: '#ffffff', border: '1px solid #cbd5e1', borderRadius: '6px', color: '#0f172a' }} /><Legend /><Line dataKey="fixed" name="고정 주기" stroke="#d97706" dot={false} isAnimationActive={false} /><Line dataKey="dqn" name="DQN" stroke="#059669" dot={false} isAnimationActive={false} /></LineChart></ResponsiveContainer></section> : <div className="presentation-empty">비교실에서 실험을 시작하면 실제 SUMO 데이터가 여기에 표시됩니다.</div>}</div>
}
